### ISSUE TITLE
Comparisons to other validator implementations

### ISSUE THREAD

**Issue by nmai** [hyperjump-io/json-schema-validator#4]
Just as a suggestion, would you consider adding some info about how JSV differentiates itself from other JS-based jsonschema validators like AJV? A full benchmark comparison is not necessary, but would be helpful for visitors to get an idea of what the primary goals of the project are- for example performance? portability? coverage all jsonschema draft versions? Really great project so far btw.

**Comment by jdesrosiers** [comment]
Thanks for the suggestion. Most of the answers are sprinkled throughout the READMEs for JSV and JSC, but it would be helpful to have a summary of features all in one place to make it easier for developers find and make a decision. I'd rather not compare directly to other implementations because it would be a nightmare to monitor every implementation for changes and keep the comparison up to date.

Regarding speed, I don't even know how it compares to other implementations at this point. Speed isn't a primary goal like it is for AJV. My primary goal was to create a generic platform that supports custom vocabularies and even other tools based on JSON Schema that are not related to validation.

Because of the trade-offs I made, I suspect that compiling a schema is comparatively slow because of how heavily promises are used. Once compiled, validation should be reasonably fast, although other than due-diligence, I haven't (yet) put any effort into fine tuning for performance.

Some of the benefits of JSV/JSC are

* No configuration fetch schemas from file or http(s)
* Add schema from code
* Supports Drafts 04/06/07/2019-09
* Support for validating with a schema that references a schema of a different draft
* Support for custom vocabularies or completely custom dialects
* Support for all Draft 2019-09 output formats
* Support for custom output formats
* Build non-validation JSON-Schema based tools with JSC
* Compiled schemas can be stored as JSON and restored later
* Works in browser and node

There's more on the roadmap, but I'll stop there for now. I might just put that list or something similar in the README.

**Comment by nmai** [comment]
That's great Jason- and yep if you put these points in README I'm sure others would find it helpful. Based on the goals/trade-offs you mentioned, I'm probably going to take a hybrid approach and continue using ajv for some validations and experiment with JSV in places where speed isn't critical. In my experience ajv works great for extremely simple schemas but unpredictably for anything more complex, hence why I've been looking for an alternative.

**Comment by jdesrosiers** [comment]
Sounds good. Please reach out if you have any questions or feedback.

**Comment by jdesrosiers** [comment]
README updated.

**Comment by jdesrosiers** [comment]
@nmai I ended up doing to some performance testing today against the FHIR schema (a notoriously large (4MB) and awful schema). My guess that Hyperjump JSV would be slow to compile and fast to validate appears to be backwards. Compared to ajv, it's more than 2x faster to compile and 6x slower to validate. Which one is more efficient will depend on the size of the schema and how many times you validate a schema per compile.

-Hyperjump JSV-
Add: 110ms
Compile: 850ms
Validate: 6ms
Total: 961ms

-ajv-
Add: 154ms
Compile: 1960ms
Validate: 1ms
Total: 2115ms

**Comment by nmai** [comment]
@jdesrosiers Really interesting numbers- thanks for running this comparison. In our case, we compile once after app launch and then we are running validations constantly so it definitely slants in favor of the ajv numbers. Any theories why the outcome was opposite your hypothesis?

**Comment by jdesrosiers** [comment]
The big surprise is that compilation is faster. I take a different approach than ajv to compilation. I build an AST, while ajv uses templates to generate code. My guess is that generating code from templates is a relatively slow process, but the code it generates can be tuned more aggressively for performance because no developer has to read the result.

I'm not surprised that ajv is faster for validation since I haven't put any effort yet into optimizing much of anything yet. However, I was surprised by how much faster it was. There are a lot of small ways I can speed things up, but I doubt it's going to get 6x faster. The biggest win I have in mind would only make compilation faster.
